backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "static/images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "images/uploads" # The src attribute for uploaded media will begin with /images/uploads


collections: # A list of collections the CMS should be able to edit
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "content/home.json"
        fields:
          - {label: Intro title, name: title, widget: string}
          - {label: Intro text, name: intro, widget: markdown}
          - {label: Intro image, name: image, widget: image}
          - label: Feature Blocks
            name: features
            required: false
            description: Feature blocks are the "three points" renamed
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - label: Feature block
                description: Please only use three blocks. If needs more please make an issue on the repo.
                name: block
                widget: list
                fields:
                  - {label: Icon, name: icon, widget: string}
                  - {label: Heading, name: heading, widget: string}
                  - {label: Paragraph, name: paragraph, widget: text}
          - label: Icon Splash
            name: icon_splash
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Text, name: text, widget: text}
              - {label: Anchor, name: anchor, widget: string}
              - {label: Href, name: href, widget: string}
          - label: Option Blocks
            name: options
            required: false
            widget: object
            fields:
            - label: Tea Dictionary
              name: dictionary
              widget: object
              fields:
                - {label: Icon, name: icon, widget: string}
                - {label: Heading, name: heading, widget: text}
                - {label: Paragraph, name: paragraph, widget: text}
            - label: Tea Quiz
              name: quiz
              widget: object
              fields:
                - {label: Icon, name: icon, widget: string}
                - {label: Heading, name: heading, widget: text}
                - {label: Paragraph, name: paragraph, widget: text}
          - label: Splash
            name: splash
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Text Splash, name: text, widget: text}
          - label: Testimonials
            name: testimonial
            required: false
            widget: list
            fields:
              - {label: Quote, name: quote, widget: text}
              - {label: Author, name: author, widget: string}
          - label: Collaborations
            name: collaborations
            required: false
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - label: Organisation
                name: organisation
                widget: list
                fields:
                  - {label: Organisation Name, name: name, widget: string}
                  - {label: Organisation Image, name: image, widget: image}
                  - {label: Organisation Link, name: href, widget: text}
          - label: Contact
            name: contact
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Text, name: text, widget: text}
              - label: Pointers
                name: points
                widget: list
                fields:
                  - {label: Icon, name: icon, widget: string}
                  - {label: paragraph, name: paragraph, widget: mardown}

      - label: "Sub page"
        name: "site"
        file: "content/site.json"
        fields:
          - {label: Global title, name: title, widget: string}
          - label: Social icons
            description: Refer to font awesome website for type (icon names), for example "facebook" would show the facebook icon, while "facebook-square" would show its squared counterpart
            name: social
            required: false
            widget: list
            fields:
              - {label: Type, name: type, widget: string}
              - {label: Link, name: href, widget: string}
          - label: Navigation
            name: nav
            widget: list
            required: false
            fields:
              - {label: Text, name: text, widget: string}
              - {label: Link, name: href, widget: string}
              - {label: Icon, name: icon, widget: string}
